id=input("Input ID:")
name=input("Input Name:")
sex=input("Input sex M/F:")
age=input("Input Age:")
add=input("Input Address:")
phone=input("Input Phone Number:")
school=input("Input School Name:")

print("\n==>11Your Information: <==\n")
print("ID: ",id)
print("Hey, ",name)
print("Sex: ",sex)
print("Age: ",age)
print("Address: ",add)
print("Phone Number: ",phone)
print("School Name: ",school)